### ISSUE TITLE
Way to select on Overview page instead of having to go to next page?

### ISSUE THREAD

**Issue by renlaur** [Khan/career-competencies#46]
<img width="1313" alt="image" src="https://github.com/Khan/career-competencies/assets/149452159/01175620-1581-4cf6-ac88-9d8a9b4cfa31">
e.g. just clicking radio buttons presented here

**Comment by renlaur** [comment]
Maybe Questionnaire tab/page can be repurposed into "Examples/Evidence" page

**Comment by nedredmond** [comment]
Well, those aren't meant to be radio buttons, but they look exactly like them. I am not a designer!

The intent was for Overview to show progress and then the Questionnaire where you give each skill its individual due consideration. Adding the ability to check them off here would be counter to that spirit... but I don't know how important that spirit is, if people find it useful.

What I'd like to do more is to find a way to represent that a skill is "checked" without looking like a form button, but this could be me being stubborn. I'll leave it to the group.

**Comment by nedredmond** [comment]
resolved by #59
