### ISSUE TITLE
Switch out example text input with resizable textarea to encourage more detail per example.

### ISSUE THREAD

**Issue by nedredmond** [Khan/career-competencies#5]
Requested by Jeanette here: https://khanacademy.slack.com/archives/C060Y8JP8D7/p1698251488591119?thread_ts=1698237299.938039&cid=C060Y8JP8D7

**Comment by SonicScrewdriver** [comment]
Happy to take this one since it seems like a good first step. I'm not seeing another way to claim it, so I'll just comment. :)

**Comment by nedredmond** [comment]
Resolved by #32
