### ISSUE TITLE
Confirm Eng. v Non-Eng. results are appropriate?

### ISSUE THREAD

**Issue by renlaur** [Khan/career-competencies#56]
Non. Eng =
<img width="840" alt="image" src="https://github.com/Khan/career-competencies/assets/149452159/2d2e8dad-31d6-44d6-9eac-2c8590aad559">

Eng. =
<img width="572" alt="image" src="https://github.com/Khan/career-competencies/assets/149452159/21dd1201-da63-4005-8452-b32fc64445d4">

**Comment by nedredmond** [comment]
@renlaur, what here are you drawing our attention to? Can you provide more details?

The competencies/skills are different from the expectations.
